// src/lib/movexosStructure.ts
export const movexosStructure = {
  0: "Write a headline about 6 words, clear and SEO-focused",
  1: "Write a subheading of around 26 words that expands the main topic",
  2: "Write an H2 subheading of around 5 words",
  3: "Write a detailed paragraph under the H2 with around 117 words",
  4: "Write an H3 subheading of around 17 words",
  5: "Write a detailed paragraph under the H3 with exactly 80 words, no less",
  6: "Write a paragraph of exactly 8 words, no more, no less",
  7: "Write a paragraph of exactly 54 words, no more, no less",
  8: "Write a paragraph of exactly 70 words, no more, no less",
  9: "Write an H4 subheading of exactly 10 words, no more, no less",
  10: "Write a paragraph of exactly 40 words, no more, no less",
  11: "Write a paragraph of exactly 60 words, no more, no less",
  12: "Write an H5 title: 'How the move works step by step'.",
  13: "Write step 1: 15 words on requesting a quote.",
  14: "Write step 2: 15 words on packing process.",
  15: "Write step 3: 15 words on transport process.",
  16: "Write step 4: 15 words on delivery process.",
  17: "Write a 65-word paragraph on what makes movexos different: trust, experience, quality.",
  18: "Write a 70-word paragraph on preparing for a move with 2 practical tips.",
  19: "Write a 50-word paragraph on movexos sustainability and eco-friendly transport.",
  20: "Write a 60-word paragraph on movexos international coverage and cross-border experience.",
  21: "Write a 70-word paragraph encouraging users to contact movexos for a personalized quote.",
  22: "Write a heading of exactly 15 words for the next section no more no less",
  23: "Write a paragraph of exactly 75 words under the heading no more no less",
  24: "Write a paragraph of exactly 40 words under the heading no more no less",
  25: "Write a paragraph of exactly 60 words under the heading, no more, no less",
  26: "Write a heading of exactly 30 words for the next section, no more, no less",
  27: "Write a paragraph of exactly 95 words under the heading, no more, no less",
  28: "Write a paragraph of exactly 70 words under the heading, no more, no less",
  29: "Write a paragraph of exactly 40 words under the heading, no more, no less",
  30: "Write a 35-word heading on popular destinations.",
  31: "Write an 80-word paragraph with city names and key phrases like 'international move'.",
  32: "Write a 60-word paragraph with 2 city tips for smooth moving.",
  33: "Write a 95-word paragraph on local rules, packing, and logistics with 3 cities.",
  34: "Write a 45-word heading on movexos advantages across Europe.",
  35: "Write a 110-word paragraph with keywords and multiple cities.",
  36: "Write a 70-word paragraph with practical international moving and customs tips.",
  37: "Write a 50-word paragraph summarizing why customers choose movexos.",
  38: "Write a 40-word heading on planning and preparing for international moves.",
  39: "Write a 100-word paragraph on early planning benefits with city mentions.",
  40: "Write a 70-word paragraph on essential packing materials and techniques.",
  41: "Write a 35-word heading on professional mover benefits.",
  42: "Write a 95-word paragraph on why experienced movers save time, include 2 cities.",
  43: "Write a 60-word paragraph on insurance and protection for belongings.",
  44: "Write a 50-word heading on efficient packing for fragile items.",
  45: "Write a 90-word paragraph on step-by-step protection for glassware, electronics, and antiques.",
  46: "Write a 70-word paragraph including Paris, Berlin, and Amsterdam for SEO relevance.",
  47: "Write a 45-word heading on understanding customs and border requirements during international moves.",
  48: "Write an 85-word paragraph on customs documentation, taxes, and clearance tips for smooth European relocations.",
  49: "Write a 75-word paragraph on how movexos assists with legal paperwork and customs forms.",
  50: "Write a 40-word heading on eco-friendly moving across Europe.",
  51: "Write a 100-word paragraph on movexos reducing emissions with efficient routes and green vehicles.",
  52: "Write a 70-word paragraph on eco-friendly packaging and recycling in international moves.",
  53: "Write a 35-word heading on customer experiences and success stories from international moves.",
  54: "Write a 90-word paragraph summarizing positive reviews and testimonials of movexos service.",
  55: "Write a 50-word paragraph quoting a satisfied customer about their European move.",
  56: "Write a 40-word heading on cost transparency and pricing for international moves.",
  57: "Write a 110-word paragraph on how movexos provides clear pricing and tailored relocation quotes.",
  58: "Write a 75-word paragraph on how to request an instant quote via movexos.",
  59: "Write a 45-word heading on long-distance moving challenges and how movexos helps.",
  60: "Write 120 words on movexos logistics, communication, and tracking. Include 3 European cities.",
};